# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "ollama-stablelm2-lambda"

[default.build.parameters]
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
image_repositories = ["HelloWorldFunction=675959947872.dkr.ecr.us-east-1.amazonaws.com/ollamastablelm2lambdaef300646/helloworldfunction19d43fc4repo"]
# resolve_image_repos = true
region = "us-east-1"
disable_rollback = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true
image_repositories = ["HelloWorldFunction=public.ecr.aws/j4y0t9y5/helloworld"]

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
