AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.12

  Sample SAM Template for ollama-stablelm2-lambda

Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
      - x86_64
      EphemeralStorage:
        Size: 1536
      MemorySize: 10240
      Timeout: 120
      ImageUri: public.ecr.aws/j4y0t9y5/h3110fr113nd/ml-inference/ollama-stablelm2-lambda:python3.11-v1
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./hello_world
      DockerTag: python3.11-v1Z
  

Outputs:
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  # Function Url
  HelloWorldFunctionUrl:
    Description: URL for the Hello World function
    Value: !GetAtt HelloWorldFunctionRole.FunctionUrl
