AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'python3.12

  Sample SAM Template for ollama-stablelm2-lambda

  '
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
      - x86_64
      EphemeralStorage:
        Size: 1536
      MemorySize: 3000
      Timeout: 120
      FunctionUrlConfig:
        InvokeMode: BUFFERED
        AuthType: AWS_IAM
      ImageUri: helloworldfunction:latest
    Metadata:
      DockerContext: /home/h3110fr13nd/Desktop/dev/cloud/aws/ollama-stablelm2-lambda/hello_world
      DockerTag: latest
      Dockerfile: Dockerfile
      SamResourceId: HelloWorldFunction
Outputs:
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - HelloWorldFunction
      - Arn
  HelloWorldFunctionUrl:
    Description: URL for the Hello World function
    Value:
      Fn::GetAtt:
      - HelloWorldFunctionUrl
      - FunctionUrl
